### ISSUE TITLE
Minio configuration requires `s3.region`

### ISSUE THREAD

**Issue by aleksandrmelnikov** [onepanelio/onepanel#405]
Related to this line in the CLI
https://github.com/onepanelio/cli/blob/bea78bcd4d1d33318e5603e4ffcae3f1170d5710/cmd/build.go#L238

Does it make sense for Minio to require a region?

**Comment by rushtehrani** [comment]
@aleksandrmelnikov I think Minio ignores that field even if it's set.

**Comment by aleksandrmelnikov** [comment]
Right, but our code will report an error if it's not set. Possibly confusing the user?

**Comment by rushtehrani** [comment]
> Right, but our code will report an error if it's not set. Possibly confusing the user?

Are you talking about the CLI code you referenced above?

**Comment by aleksandrmelnikov** [comment]
Correct. I suggest we have the CLI code not check the "region" if it's minio configuration.

**Comment by Vafilor** [comment]
@rushtehrani Awaiting your feedback

**Comment by rushtehrani** [comment]
> Correct. I suggest we have the CLI code not check the "region" if it's minio configuration.

I think this is the right approach, I'm assuming that if url != `s3.awsamazon.com`, then we assume it's Minio? cc @Vafilor

**Comment by Vafilor** [comment]
@rushtehrani cc @aleksandrmelnikov 
We'll need to also check for azure and gcs, I believe they have their own urls.
If none of those, then we can assume minio.

@aleksandrmelnikov If this sounds good to you, let's move this ticket to in progress or todo.

**Comment by rushtehrani** [comment]
@Vafilor gcs and az have a different configuration and should not be affected by this.
