### ISSUE TITLE
(question) Deploying to multiple local nodes

### ISSUE THREAD

**Issue by MRIIOT** [onepanelio/onepanel#608]
Is there a guide for deploying to multiple local nodes with multiple GPUs each?

**Comment by aleksandrmelnikov** [comment]
Thanks for the inquiry!

We don’t have a guide for this yet. What you can try is  the MicroK8s installation and then following this: https://microk8s.io/docs/clustering
We recommend starting with Ubuntu if possible.

We'll develop a guide for this process though, thank you.

**Comment by rushtehrani** [comment]
Multi-node MicroK8s deployment on Linux machines is now available in the newly released v0.20.0. See updated [quick start](https://docs.onepanel.ai/docs/getting-started/quickstart) for instructions.
