### ISSUE TITLE
Multi-node Microk8s deployment on Ubuntu

### ISSUE THREAD

**Issue by inohmonton99** [onepanelio/onepanel#732]
Update documentation and code to support multi-node Microk8s deployment on Ubuntu.

**Comment by rushtehrani** [comment]
Related issues #754 #741 #734

**Comment by rushtehrani** [comment]
MicroK8s deployment on Linux machines is now available in the newly released v0.20.0. See updated [quick start](https://docs.onepanel.ai/docs/getting-started/quickstart) for instructions.

**Comment by skytodmoon** [comment]
Hello guys, no tips on how to add node with Microk8s, Any suggestions?
https://docs.onepanel.ai/docs/deployment/components/nodes/
