### ISSUE TITLE
Self hosted OnePanel

### ISSUE THREAD

**Issue by AlgirdasKartavicius** [onepanelio/onepanel#741]
Can i host OnePanel on my own machine without using any cloud provider? 
Do you have any tutorial how to deploy it on local machine?

**Comment by rushtehrani** [comment]
@AlgirdasKartavicius We are adding a new guide for running Onepanel locally on single and mutli-node MicroK8s cluster on Ubuntu. Out of curiosity, what operating system are you currently using on your local machine?

**Comment by AlgirdasKartavicius** [comment]
Currently i am using windows, but i plan to buy new computer and install ubuntu for machine learning.

**Comment by xyc2690** [comment]
> @AlgirdasKartavicius We are adding a new guide for running Onepanel locally on single and mutli-node MicroK8s cluster on Ubuntu. Out of curiosity, what operating system are you currently using on your local machine?

Look forward to your guide! 
Would it be ready by the end of 2020？

**Comment by rushtehrani** [comment]
> Would it be ready by the end of 2020？

Yes, hopefully well before then.

**Comment by arasharchor** [comment]
@rushtehrani 
Any news on this thread?

I am using Ubuntu 16.04 and Ubuntu 18.04. I have a rented dedicated server on which I would like to load openpanelio.

**Comment by xyc2690** [comment]
> 
> 
> @rushtehrani
> Any news on this thread?
> 
> I am using Ubuntu 16.04 and Ubuntu 18.04. I have a rented dedicated server on which I would like to load openpanelio.

I have tried to deploy onepanel on a single node machine, and it works. Hope it will help.
https://github.com/onepanelio/core-docs/tree/v0.13.0/docs/deployment/single-node

**Comment by rushtehrani** [comment]
Multi-node MicroK8s deployment on Linux machines is now available in the newly released v0.20.0. See updated [quick start](https://docs.onepanel.ai/docs/getting-started/quickstart) for instructions.
