### ISSUE TITLE
KUBECONFIG=./kubeconfig opctl apply

### ISSUE THREAD

**Issue by Sirius6** [onepanelio/onepanel#754]
When I installed onepanel, the final deployment was stuck：

[root@localhost home]# KUBECONFIG=./kubeconfig opctl apply
Starting deployment...

2020/11/30 16:23:13 namespace/application-system unchanged
customresourcedefinition.apiextensions.k8s.io/applications.app.k8s.io configured
clusterrole.rbac.authorization.k8s.io/application-manager-role configured
clusterrolebinding.rbac.authorization.k8s.io/application-manager-rolebinding configured
service/application-controller-manager-service unchanged
statefulset.apps/application-controller-manager unchanged

Excuse me, what is this question?

**Comment by inohmonton99** [comment]
this specific step usually takes time because it's preparing all requisites for the deployment, did it return any error?

**Comment by rushtehrani** [comment]
@Sirius6 which Kubernetes version and cloud provider are you deploying to?

**Comment by Sirius6** [comment]
I deployed a single machine in a local environment, refer to the official website https://docs.onepanel.ai/docs/deployment/single-node/microk8s/#install-microk8s-with-multipass for deployment

**Comment by Sirius6** [comment]
@rushtehrani @inohmonton99

**Comment by rushtehrani** [comment]
@Sirius6 which operating system are you using? Just a heads up, we're working on updated docs for latest Microk8s on Ubuntu so it might be best to wait for those updates or try deploying on one of the cloud providers for now.

**Comment by Sirius6** [comment]
I am currently installing on the stand-alone version, and your reply is that the documentation for the current stand-alone deployment method has not been updated, or does it depend on cloud services?

**Comment by Sirius6** [comment]
@rushtehrani

**Comment by rushtehrani** [comment]
> @rushtehrani At present, I am installing on the local ubuntu, and I do not rely on cloud service providers. Will you support local installation and deployment after updating?

Yes, we are working on better docs (and a simpler process) for single and multi node deployments to latest Microk8s on Ubuntu.

**Comment by Sirius6** [comment]
> > @rushtehrani At present, I am installing on the local ubuntu, and I do not rely on cloud service providers. Will you support local installation and deployment after updating?
> 
> Yes, we are working on better docs (and a simpler process) for single and multi node deployments to latest Microk8s on Ubuntu.

Okay thank you! How long does this update process take?

**Comment by rushtehrani** [comment]
We’re currently actively working on it and will know more by end of this week. I will update this issue and release notes as soon as we have something that works without issues.

**Comment by Sirius6** [comment]
> We’re currently actively working on it and will know more by end of this week. I will update this issue and release notes as soon as we have something that works without issues.

Okay thank you!

**Comment by rushtehrani** [comment]
MicroK8s deployment on Linux machines is now available in the newly released v0.20.0. See updated [quick start](https://docs.onepanel.ai/docs/getting-started/quickstart) for instructions.
