### ISSUE TITLE
Deploy onepanel locally in minikube (single node cluster)

### ISSUE THREAD

**Issue by prakashsingh21** [onepanelio/onepanel#857]
I tried to deploy onepanel in minikube (single node cluster)
Steps which we followed:
1. Install VirtualBox Hypervisor, Minikube and Kubectl in VM (Standard_B4ms --> CPU: 4, RAM: 16 GB) Ubuntu(18.04) linux.
2. Install opctl, refered link: https://github.com/onepanelio/core/releases/tag/v0.17.0
3. `opctl init --provider minikube     --artifact-repository-provider s3`
4. After running the step3 command got 2 files i.e. config.yaml  and param.yaml then I edit the param.yaml accordingly (sharing the edited param.yaml file without credential).

After executing all the above steps I run `optctl apply` command it gives a error, sharing the error screenshot in attachment. 
If possible kindly share the doc to deploy the onepanel in minikube.

Thankyou

**Screenshots**
![error](https://user-images.githubusercontent.com/77429694/105990715-e6647100-60c8-11eb-9458-a431881532fc.PNG)

**Param.yaml File**
 
[param-file.txt](https://github.com/onepanelio/core/files/5880163/param-file.txt)

**Comment by xyc2690** [comment]
Try this doc.  I managed deploying onepanel on a CPU machine.
https://github.com/onepanelio/core-docs/tree/v0.13.0/docs/deployment/single-node

**Comment by rushtehrani** [comment]
If you want to run on a single node CPU, the doc @xyc2690 should help, but your mileage may vary.

We can't currently support local deployments until we have a stable solution with [MicroK8s on Ubuntu](https://github.com/onepanelio/core/issues/732). The goal is to make local deployment work on single-node and multi-node machines with both CPUs and GPUs.

**Comment by xyc2690** [comment]
> 
> 
> If you want to run on a single node CPU, the doc @xyc2690 should help, but your mileage may vary.
> 
> We can't currently support local deployments until we have a stable solution with [MicroK8s on Ubuntu](https://github.com/onepanelio/core/issues/732). The goal is to make local deployment work on single-node and multi-node machines with both CPUs and GPUs.

Does there any plan for minikube？I currently stuck on the problems of configuring single node with GPU.

**Comment by prakashsingh21** [comment]
Thank you so much for the documentation you provided (@xyc2690 ) it helped us in  deploying onepanel on minikube.
 
After deploying one-panel on minikube we are still facing some of the issues while launching a workspace.

issues :
1. We tried launching a workspace but it stays in pending state. The reason behind that was due to pod affinity.(We did some experiment from our end we gave the same label to node which is mentioned in  deployment file of a pod, it worked but then it gave us the error of (port bind 80 is already in use) then we changed  the port no. of istioingress but that also didn't worked for us.

2. We gave the different port number but still we were not able to access it.
Can you help us with the issues we are facing while launching a workspace?

Yes, our future plan is to use onepanel in minikube, but before that I need to do some testing/experiment.

Hope so, soon we get stable onepanel version for minikube.

**Comment by rushtehrani** [comment]
@xyc2690 @prakashsingh21 we weren't planning on supporting Minikube going forward since MicroK8s can support both single node and multi-node in a production setting. 

The issues we're seeing with Minikube are that it was never meant to be anything more than a dev Kubernetes distor and its multi-node support is currently experimental. Can you clarify why you would prefer Minikube over MicroK8s?

**Comment by prakashsingh21** [comment]
@rushtehrani okay, we will try with microk8s, can you please share the sample params.yaml file for microk8s. Actually the documentation which @xyc2690 provided in that param.yaml file is not available.
[link](https://github.com/onepanelio/core-docs/blob/v0.13.0/docs/deployment/configuration/files#sections)

**Comment by rushtehrani** [comment]
> okay, we will try with microk8s, can you please share the sample params.yaml file for microk8s.

To clarify, we're working on this still. You can see our [initial attempt](https://github.com/onepanelio/core-docs/blob/v0.13.0/docs/deployment/single-node/microk8s.md) but that had issues and we decided to remove the documentation and work on a more stable deployment before releasing it to the community.

**Comment by rushtehrani** [comment]
Multi-node MicroK8s deployment on Linux machines is now available in the newly released v0.20.0. See updated [quick start](https://docs.onepanel.ai/docs/getting-started/quickstart) for instructions.
