### ISSUE TITLE
Node-red workspace template 

### ISSUE THREAD

**Issue by dsyou20** [onepanelio/onepanel#859]
**Is your feature request related to a problem? Please describe.**
how to create ensemble inferencing with node-red

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rushtehrani** [comment]
We don’t fully have Node-RED integrated - it is in our templates as an example Workspace you can run. You could be easily use the Workflows for ensemble inference though, see this [example](https://github.com/onepanelio/templates/tree/master/workflows/ensemble-inference) and this [blog post](https://www.onepanel.io/blog/ensembling-multiple-object-detection-models-on-onepanel)

**Comment by rushtehrani** [comment]
Closing assuming this is not an issue anymore.
