### ISSUE TITLE
Auto annoatation with custom models and infernce scripts with cvat

### ISSUE THREAD

**Issue by Pramod-ReflectiveAi** [onepanelio/onepanel#861]
HI @rushtehrani 

I was looking for a feature where we can write our own inference scrips from our custom model pipelines and generate the labels for cvat auto annotation

Is this any option for this, doing auto annotation and training models with the only supported models is very restrictive 

Please let me know, Thanks

**Comment by rushtehrani** [comment]
Hi @Pramod-ReflectiveAi, yes this is currently possible as outlined in [this doc](https://docs.onepanel.ai/docs/getting-started/use-cases/computervision/annotation/cvat/adding_custom_model). 

We have simplified this even more in our upcoming 0.18.0 release. Expect to have updated docs and the release out by early next week.

**Comment by PGCodehub** [comment]
Hi @rushtehrani , 

Thanks, this cloud help in training 

Is it possible to create same for auto annotation also, where I create a inference script from custom trained model and generate labels in certain format that cvat can take? 

Cloud you please point me to article on auto annotation on cvat with custom model script

Thanks

**Comment by rushtehrani** [comment]
> Is it possible to create same for auto annotation also, where I create a inference script from custom trained model and generate labels in certain format that cvat can take?

Yes, you can upload any model/labels that are trained with the built-in training Workflows or your own custom training Workflow into CVAT as [described here](https://docs.onepanel.ai/docs/getting-started/use-cases/computervision/annotation/cvat/cvat_automatic_annotation). Again, this will be even more simplified in the upcoming release (0.18.0)

**Comment by javoweb** [comment]
Hi @PGCodehub , I think it is not currently possible to have custom auto annotation scripts for inference. In the meantime, you can use the same tools for custom training workflows to perform inference and give a file in a CVAT-compatible format as output. MS Coco is a friendly and widespread format to work with. We support data-augmentation in this way as you can see in [this example](https://github.com/onepanelio/templates/tree/release-v0.18.0/workflows/albumentations-preprocessing).

Then you can use the "Upload Annotations" feature to use them back in CVAT.

So you will need two workflows, one for training and another for inference, hence, you can use the same script with different flags or parameters for train and inference.
