### ISSUE TITLE
Onepanel mutil deploy in local machine 

### ISSUE THREAD

**Issue by qzwlinux** [onepanelio/onepanel#885]
Hello , Is there a local multi-machine deployment method currently?
I use minikube locally to deploy on a single machine successfully and can be used, but I don’t know how to use multi-machine deployment.
Seeing that local multi-machine deployment will be added in the v0.19.0 version, when is the deadline? #732 
Thanks

**Comment by rushtehrani** [comment]
Hello, we're still working on this feature and unfortunately it will not make it into v0.19.0. We'll update the issue you referenced once we have a stable deployment process.

**Comment by GGDRriedel** [comment]
I just want to reinforce how useful this would be

**Comment by rushtehrani** [comment]
Multi-node MicroK8s deployment on Linux machines is now available in the newly released v0.20.0. See updated [quick start](https://docs.onepanel.ai/docs/getting-started/quickstart) for instructions.
