### ISSUE TITLE
Present Onepanel at Argo community meeting  

### ISSUE THREAD

**Issue by alexec** [onepanelio/onepanel#891]
Come and present at our community meeting. People would love to learn more.

**Comment by rushtehrani** [comment]
Sounds great @alexec, we’ll get something prepared for the next one if that works. I believe next one is in two weeks?

**Comment by alexec** [comment]
Cool.  Are you on the Argo Slack? It’s be good to chat beforehand.

**Comment by rushtehrani** [comment]
> Cool. Are you on the Argo Slack? It’s be good to chat beforehand.

Great! Will ping you in Argo Slack

**Comment by rushtehrani** [comment]
Thanks to the Argo team for inviting us to present. [View recording](https://www.youtube.com/watch?v=FnpXyg-5W_c&t=1156s).
