### ISSUE TITLE
Unable to host onepanel in domain

### ISSUE THREAD

**Issue by akshatamk** [onepanelio/onepanel#901]
Hello,
I'm setting up the one panel on azure kubernetes using azure virtual instances. In editing params.yaml file I'm not getting what should be the  domain and fqdn.I tried with VM DNS name and then setting up the DNS zone and record for the same. But It's not working. Getting error as this site can not be reached. Please help me what should be the domain and FQDN.

Thank you

**Comment by rushtehrani** [comment]
Hi @akshatamk, if your domain for Onepanel is `sub.domain.com`, then the FQDN to access Onepanel UI could be `app.sub.domain.com`. Note that currently, you would need a real domain name for this to work.

**Comment by akshatamk** [comment]
Thankyou @rushtehrani for your response.
Yes I do have  real domain name for  ex-eastus.cloudapp.azure.com
The domain for onepanel is - eastus.cloudapp.azure.com
FQDN-app."server_name".eastus.cloudapp.azure.com
still not working

**Comment by rushtehrani** [comment]
@akshatamk following up from the Slack conversation, were you able to address this?

**Comment by FlorentF9** [comment]
Hi, I also struggle to find how to set the domain name of my EC2 instance where I want to host onepanel.
It seems that there is no longer a Slack? 
Thanks for your support
