### ISSUE TITLE
local deploy error

### ISSUE THREAD

**Issue by pingchesu** [onepanelio/onepanel#914]
**Describe the bug**

***`opctl app status` error***
I followed the quickstart tutorial, and deploy onepanel with microk8s.
All the steps work fine. However, when I finished `KUBECONFIG=./kubeconfig opctl apply`, the console shows 
```Deployment is complete.


In your /etc/hosts file, add '192.168.99.0' and point it to cv-trainer.japaneast.cloudapp.azure.com

In your DNS, add an A record for *.japaneast.cloudapp.azure.com and point it to '192.168.99.0'
Once complete, your application will be running at http://cv-trainer.japaneast.cloudapp.azure.com
```
And I run `opctl app status`, but I got the error:

```
Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
```
I check the listening port with following command but get nothing:
```bash
sudo netstat -tnlp | grep 8080
```
Then I execute the following command:
```bash
microk8s kubectl get pods -A
```
![image](https://user-images.githubusercontent.com/33800609/115335462-dba11000-a1cf-11eb-90ea-60a06af488bf.png)

It's seems the service is running.

Have you ever encounter this problem?

Our any suggestion to fix this problems?

Many thanks!!

**`opctl` version**
```bash
$ opctl version

CLI version: 0.21.0
Manifest version: v0.21.0
API version: v0.21.0
Web UI version: v0.21.0
```
```bash
$ snap microk8s info
```
![image](https://user-images.githubusercontent.com/33800609/115335758-6e41af00-a1d0-11eb-8836-6cbb07a6a951.png)

**Comment by Vafilor** [comment]
Hi @pingchesu ,

When deploying locally, you can use any domain/fqdn. I usually use

```yaml
domain: "onepanel.test"
fqdn: "app.onepanel.test"
```

The message about the A record might be a bug when using microk8s, I'll look into it.

Also, when running app status, make sure to use the same kubeconfig file.

```bash
KUBECONFIG=./kubeconfig opctl app status
```

**Comment by pingchesu** [comment]
@Vafilor 
Really thanks!!
The following command works for me
```
KUBECONFIG=./kubeconfig opctl app status
```
![image](https://user-images.githubusercontent.com/33800609/115350139-4e69b580-a1e7-11eb-922b-614d5a2b926d.png)

However my deploy situation is that I have to create a remote VM on cloud (No aks,gks,eks), the only way I can access to VM is through ssh or browser.
Can I access the openpanel (with microk8s) from remote by using browser?

**Comment by Vafilor** [comment]
@pingchesu 

Sure thing.

Yes, but there are a few additional steps to do so.

I just updated our docs to document how to do this.

https://docs.onepanel.ai/docs/deployment/configuration/remote-microk8s

**Comment by pingchesu** [comment]
@Vafilor 
Really appreciate for the document!!! 
I got stuck when using nginx as proxy yesterday!!
I will follow the remote-microk8s document and try it later!!

**Comment by rushtehrani** [comment]
Closing assuming this is resolved, feel free to open if issue is not resolved.

**Comment by skytodmoon** [comment]
> @Vafilor Really appreciate for the document!!! I got stuck when using nginx as proxy yesterday!! I will follow the remote-microk8s document and try it later!!

Hi, guys. Have you successed to deploy the onpanel on a local machine, I met the same problem.
