### ISSUE TITLE
ip address missing on apply command

### ISSUE THREAD

**Issue by inohmonton99** [onepanelio/onepanel#927]
**Describe the bug**

**`opctl` version**
```bash
$ opctl version

CLI version: v1.0.0-rc.1
Manifest version: v1.0.0-rc.1
API version: v1.0.0-rc.1
Web UI version: v1.0.0-rc.1
```

**`opctl init` command**
You can find this at the top of your `params.yaml` file.
opctl init --provider gke ^
  --artifact-repository-provider gcs ^
  --gpu-device-plugins nvidia ^
  --database

**Kubernetes information**
 - Cloud provider: GKE
 - Kubernetes version: 1.19.9-gke.1900

**Machine information**
- OS: Windows 10
- Browser: Edge

**Screenshots**
![image](https://user-images.githubusercontent.com/37641302/125513092-77df0f16-cb43-4b0c-802a-71e8d3a405a9.png)

**Comment by Vafilor** [comment]
This should be fixed in v1.0.0-rc.1

Please re-open if it is not.
