### ISSUE TITLE
Pls someone can detailly explain how start onepanel !!!!!!!!!!!!!!!!!!!!!!!!!!! 

### ISSUE THREAD

**Issue by sevaraMS** [onepanelio/onepanel#929]
Hello, I want to start work with obepanel, but when I go to quick start I could not understand anything. I use windows 10. Pls how can I run it and work on it. The documentation and explanation are very bad. Pls do something for very beginners. HOW CAN I LAUNCH IT NOT USING Azure AKS Amazon EKS Google Cloud GKE MicroK8s THIS BLA BLA BLA THINGS. Thank you

**Comment by Vafilor** [comment]
Hi, 

It looks like we're discussing this with you in our slack channel.

I'm going to close this issue as the conversation is there. 

Feel free to re-open with any specific questions.
