### ISSUE TITLE
Filesyncer - Object Storage files inside folders aren't visible

### ISSUE THREAD

**Issue by inohmonton99** [onepanelio/onepanel#932]
**Describe the bug**
When trying to access files under object storage, the files aren't visible inside folders, though I was able to sync the data into the workspace even though they are not visible in the UI

**`opctl` version**
```bash
$ opctl version

CLI version: v1.0.0-rc.1
Manifest version: v1.0.0-rc.1
API version: v1.0.0-rc.1
Web UI version: v1.0.0-rc.1
```

**`opctl init` command**
opctl init --provider aks --artifact-repository-provider s3 --gpu-device-plugins nvidia

**Kubernetes information**
 - Cloud provider: AKS
 - Kubernetes version: 1.19.11

**Machine information**
- OS: Windows 10
- Browser: Edge

**Screenshots**
![image](https://user-images.githubusercontent.com/37641302/126214925-5fbf130c-a913-420b-b847-b984eca83f41.png)

**Comment by Vafilor** [comment]
This should be fixed v1.0.0-rc.1.

Please re-open if this issue is still there.
